name: starzen
favicon: null
layout_spectrum: 0.0044893305748701096
typography_spectrum: 0.10028134752064943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4316162276081741
  lightness: 0.8394471949432045
  saturation: 0.33576175500638783
  rhythmicContrast: 0.474120611557737
purpose: []
